plugins {
    id 'com.android.application'
}

android {
    namespace 'uk.co.divadiow.hotspotdevices'
    compileSdk 36

    defaultConfig {
        applicationId 'uk.co.divadiow.hotspotdevices'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
